### ISSUE TITLE
Can not get output in CBR version 6.4.0

### ISSUE THREAD

**Issue by alibay7** [carbonblack/tau-tools#16]
File "navgen.py", line 503, in <module>
    main()
  File "navgen.py", line 469, in main
    tid_dict = generate_tid_dict(data_from_cbr)
  File "navgen.py", line 355, in generate_tid_dict
    if "windows" in threat_report['tags'] or "linux" in threat_report['tags'] or "macos" in threat_report['tags']:
KeyError: 'tags'

**Comment by JimmyAstle** [comment]
Hi @alibay7 

Have you tried to running this recently? If you are still having issues let us know but I will close this out due to age.
