### ISSUE TITLE
Invalid Syntax error in navgen.py

### ISSUE THREAD

**Issue by meyerscott42** [carbonblack/tau-tools#2]
I'm attempting to run the navgen.py, but keep getting an error after I input the Cb Response URL.
Below is the syntax I get.  I have replaced the URL in this extract to the default example URL, but I get the exact same error when I add in our true URL:

[!] To find your API key, login to your Cb Response UI and navigate to the profile section.
[!] Here, enter the full url of your Cb Response instance. Example: https://bugcrowd.my.carbonblack.io
[*] > https://bugcrowd.my.carbonblack.io
Traceback (most recent call last):
  File "navgen.py", line 499, in <module>
    main()
  File "navgen.py", line 456, in main
    api_key, url = get_auth()
  File "navgen.py", line 12, in get_auth
    full_url = input("[!] Here, enter the full url of your Cb Response instance. Example: https://bugcrowd.my.carbonblack.io\n[*] > ")
  File "<string>", line 1
    https://bugcrowd.my.carbonblack.io
         ^
SyntaxError: invalid syntax

**Comment by meyerscott42** [comment]
Looks like the script requires Python3.
My error was caused by running the NavGen script in Python2.7.

**Comment by alibay7** [comment]
File "navgen.py", line 503, in <module>
    main()
  File "navgen.py", line 469, in main
    tid_dict = generate_tid_dict(data_from_cbr)
  File "navgen.py", line 355, in generate_tid_dict
    if "windows" in threat_report['tags'] or "linux" in threat_report['tags'] or "macos" in threat_report['tags']:
KeyError: 'tags'
